# Generated by Django 2.1.7 on 2019-03-13 13:59
'''
Converts the top page on the site into a Homepage type
'''
from django.db import migrations
from kdl_wagtail.core.utils import migrate_wagtail_page_type


def convert_pages(apps, schema_editor):
    def select(qs):
        # select the top page only
        ret = qs.filter(depth=2)
        return ret

    mapping = {
        'models': {
            'from': ('kdl_wagtail_core', 'RichTextPage'),
            'to': ('field_wagtail', 'Homepage'),
        },
        'select': select,
    }
    count = migrate_wagtail_page_type(apps, schema_editor, mapping)


class Migration(migrations.Migration):

    dependencies = [
        ('field_wagtail', '0002_homepage'),
    ]

    operations = [
        migrations.RunPython(convert_pages),
    ]
