# Generated by Django 2.1.7 on 2019-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_wagtail', '0004_mailinglistformpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglistformpage',
            old_name='confirmation_message',
            new_name='success_message',
        ),
        migrations.AddField(
            model_name='mailinglistformpage',
            name='error_message',
            field=models.TextField(blank=True, help_text='Confirmation message to users who have just signed up'),
        ),
    ]
