# Generated by Django 2.1.7 on 2019-03-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_wagtail', '0005_auto_20190324_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistformpage',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message in case the use cannot re-subscribe'),
        ),
    ]
