# Generated by Django 2.2.13 on 2020-06-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0004_auto_20191211_1917'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('field_wagtail', '0006_auto_20190329_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDublinCoreResource',
            fields=[
                ('dublincoreresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dublincore_resource.DublinCoreResource')),
                ('wagtail_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtaildocs.Document')),
                ('wagtail_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('dublincore_resource.dublincoreresource',),
        ),
        migrations.CreateModel(
            name='FieldDublinCoreResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_wagtail.FieldDublinCoreResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
