# Generated by Django 2.2.14 on 2020-07-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('field_wagtail', '0010_alter_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimelinePage',
        ),
    ]
