# Generated by Django 2.2.14 on 2020-07-20 16:39

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_timeline', '0007_auto_20200616_1009'),
        ('field_wagtail', '0012_remove_field_dublin_core_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTimelineEventSnippet',
            fields=[
                ('fieldtimelineevent_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True, primary_key=True,
                     serialize=False,
                     to='field_timeline.FieldTimelineEvent'
                 )
                 ),
            ],
            bases=(
                wagtail.search.index.Indexed,
                'field_timeline.fieldtimelineevent'),
        ),
    ]
