# Generated by Django 2.2.14 on 2020-07-20 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('field_timeline', '0007_auto_20200616_1009'),
        ('field_wagtail', '0012_remove_field_dublin_core_resource'),
    ]

    operations = [

    ]
