# Generated by Django 2.2.14 on 2020-07-21 13:08

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_timeline', '0007_auto_20200616_1009'),
        ('dublincore_resource', '0004_auto_20191211_1917'),
        ('wagtailimages', '0022_uploadedimage'),
        ('field_wagtail', '0013_fieldtimelineeventsnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOralHistory',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')
                 ),
                ('speaker', models.CharField(default='', max_length=256)),
                ('place', models.CharField(default='', max_length=256)),
                ('era', models.CharField(default='', max_length=128)),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='FieldTimelineCategory',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')
                 ),
                ('category_name', models.CharField(
                    blank=True, max_length=256)
                 ),
            ],
        ),
        migrations.CreateModel(
            name='FieldTimelineEvent',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')
                 ),
                ('unique_id', models.CharField(blank=True, max_length=256)),
                ('start_date_year', models.IntegerField(default=0)),
                ('start_date_month', models.IntegerField(default=0)),
                ('start_date_day', models.IntegerField(default=0)),
                ('end_date_year', models.IntegerField(default=0)),
                ('end_date_month', models.IntegerField(default=0)),
                ('end_date_day', models.IntegerField(default=0)),
                ('headline', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('tier', models.IntegerField(default=0)),
                ('who', models.CharField(default='', max_length=256)),
                ('additional_information', models.TextField(
                    blank=True, default='')
                 ),
                ('category', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.PROTECT,
                    to='field_wagtail.FieldTimelineCategory')
                 ),
                ('linked_events', models.ManyToManyField(
                    related_name='_fieldtimelineevent_linked_events_+',
                    to='field_wagtail.FieldTimelineEvent')
                 ),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='FieldTimelineResource',
            fields=[
                ('dublincoreresource_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True, serialize=False,
                    to='dublincore_resource.DublinCoreResource')
                 ),
                ('filename', models.CharField(default='', max_length=256)),
                ('image_ref', models.CharField(blank=True, max_length=256)),
                ('caption', models.TextField(blank=True, default='')),
                ('credit', models.CharField(blank=True, max_length=256)),
                ('link_url', models.CharField(max_length=512, null=True)),
                ('resource_type', models.CharField(choices=[
                    ('I', 'IMAGE'), ('D', 'DOCUMENT'), ('A', 'AUDIO'),
                    ('V', 'VIDEO')
                ], default='I', max_length=64)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Resource',
            },
            bases=('dublincore_resource.dublincoreresource',),
        ),
        migrations.CreateModel(
            name='FieldTimelineResourceImage',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')
                 ),
                ('image', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    to='wagtailimages.Image')
                 ),
                ('resource', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    to='field_wagtail.FieldTimelineResource')
                 ),
            ],
        ),
        migrations.DeleteModel(
            name='FieldTimelineEventSnippet',
        ),
        migrations.AddField(
            model_name='fieldtimelineevent',
            name='resource',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='field_wagtail.FieldTimelineResource'
            ),
        ),
        migrations.AddField(
            model_name='fieldoralhistory',
            name='timeline_event',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                to='field_wagtail.FieldTimelineEvent'
            ),
        ),
    ]
