# Generated by Django 2.2.14 on 2020-07-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dublincore_resource', '0004_auto_20191211_1917'),
        ('field_wagtail', '0014_add_oral_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldoralhistory',
            name='rights',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='dublincore_resource.DublinCoreRights'
            ),
        ),
    ]
