# Generated by Django 2.2.14 on 2020-07-24 12:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('field_wagtail', '0014_fieldtimeline_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTimelinePage',
            fields=[
                (
                    'page_ptr', models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True, primary_key=True, serialize=False,
                        to='wagtailcore.Page')
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FieldTimelineEventItem',
            fields=[
                (
                    'id', models.AutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')
                ),
                ('sort_order',
                 models.IntegerField(blank=True, editable=False, null=True)
                 ),
                ('event',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='+',
                                   to='field_wagtail.FieldTimelineEvent')
                 ),
                ('page', modelcluster.fields.ParentalKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='related_events',
                    to='field_wagtail.FieldTimelinePage')
                 ),
            ],
            options={
                'verbose_name': 'Timeline events',
                'abstract': False,
                'verbose_name_plural': 'Timeline events',
                'ordering': ['sort_order'],
            },
        ),
    ]
