# Generated by Django 2.2.14 on 2020-07-28 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('field_wagtail', '0018_resource_clusterable'),
    ]

    operations = [
    ]
