# Generated by Django 2.2.14 on 2020-07-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_wagtail', '0020_add_next_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtimelinecategory',
            options={
                'verbose_name': 'Timeline Category',
                'verbose_name_plural': 'Timeline Categories'},
        ),
        migrations.AlterField(
            model_name='fieldtimelineevent',
            name='linked_events',
            field=models.ManyToManyField(
                blank=True, related_name='_fieldtimelineevent_linked_events_+',
                to='field_wagtail.FieldTimelineEvent'),
        ),
        migrations.AlterField(
            model_name='fieldtimelineevent',
            name='next_event',
            field=models.ForeignKey(
                blank=True, help_text='Next event in theme', null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='previous_event',
                to='field_wagtail.FieldTimelineEvent'),
        ),
        migrations.AlterField(
            model_name='fieldtimelineevent',
            name='who',
            field=models.CharField(
                blank=True, default='', max_length=256),
        ),
    ]
