# Generated by Django 2.2.14 on 2020-07-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_wagtail', '0021_blank_event_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtimelineevent',
            name='resource',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='field_wagtail.FieldTimelineResource'),
        ),
    ]
