# Generated by Django 2.2.15 on 2021-04-19 14:50

import django.db.models.deletion
import wagtail.images.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_wagtail', '0023_fieldimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldImageRendition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('filter_spec',
                 models.CharField(db_index=True, max_length=255)),
                ('file',
                 models.ImageField(
                     height_field='height',
                     upload_to=wagtail.images.models.get_rendition_upload_to,
                     width_field='width'
                 )
                 ),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key',
                 models.CharField(blank=True, default='', editable=False,
                                  max_length=16)),
                ('image',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='renditions',
                                   to='field_wagtail.FieldImage')),
            ],
            options={
                'unique_together': {
                    ('image', 'filter_spec', 'focal_point_key')},
            },
        ),
    ]
