# Generated by Django 2.2.15 on 2021-04-19 14:57

from django.db import migrations


def copy_images(apps, schema_editor):
    """ Copy existing wagtail image records into new image model"""

    FieldImage = apps.get_model('field_wagtail', 'FieldImage')
    Image = apps.get_model('wagtailimages', 'Image')
    django_content_type = apps.get_model('contenttypes', 'contenttype')
    tagged_item_model = apps.get_model('taggit', 'TaggedItem')

    images = Image.objects.all()
    new_images = []
    for image in images:
        new_images.append(FieldImage(
            id=image.id,
            title=image.title,
            file=image.file,
            width=image.width,
            height=image.height,
            created_at=image.created_at,
            focal_point_x=image.focal_point_x,
            focal_point_y=image.focal_point_y,
            focal_point_width=image.focal_point_width,
            focal_point_height=image.focal_point_height,
            file_size=image.file_size,
            collection=image.collection,
            uploaded_by_user=image.uploaded_by_user,
            alt_text=''
        ))

    FieldImage.objects.bulk_create(new_images)

    ct_extended_model, created = django_content_type.objects.get_or_create(
        app_label='field_wagtail',
        model='fieldimage'
    )
    ct_wagtail_model = django_content_type.objects.get(
        app_label='wagtailimages',
        model='image'
    )

    tagged_item_model.objects.filter(
        content_type_id=ct_wagtail_model.id).update(
        content_type_id=ct_extended_model.id
    )


class Migration(migrations.Migration):

    dependencies = [
        ('field_wagtail', '0024_fieldimagerendition'),
    ]

    operations = [
        migrations.RunPython(copy_images)
    ]
