# Generated by Django 2.2.23 on 2022-06-20 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={
                'ordering': ('domain',), 'verbose_name': 'site',
                'verbose_name_plural': 'sites'
            },
        ),
    ]
