# Generated by Django 2.1.7 on 2020-06-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_timeline', '0002_alter_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtimelineevent',
            name='linked_events',
        ),
        migrations.AddField(
            model_name='fieldtimelineevent',
            name='linked_events',
            field=models.ManyToManyField(null=True, related_name='_fieldtimelineevent_linked_events_+', to='field_timeline.FieldTimelineEvent'),
        ),
    ]
