# Generated by Django 2.1.7 on 2020-06-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_timeline', '0003_alter_linked_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtimelineresource',
            old_name='url',
            new_name='link_url',
        ),
    ]
