# Generated by Django 2.1.7 on 2020-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_timeline', '0005_alter_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtimelineresource',
            name='date',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fieldtimelineresource',
            name='filename',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='fieldtimelineresource',
            name='rights',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fieldtimelineresource',
            name='title',
            field=models.CharField(default='', max_length=512),
        ),
    ]
