# Generated by Django 2.2.13 on 2020-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_timeline', '0006_alter_resource_add_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtimelineevent',
            name='linked_events',
            field=models.ManyToManyField(
                related_name='_fieldtimelineevent_linked_events_+',
                to='field_timeline.FieldTimelineEvent'),
        ),
    ]
