#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

#tar xzf /node_modules.tar.gz

python manage.py migrate
#python manage.py wagtail_update_index
python manage.py collectstatic --no-input
python manage.py compress

## GN: disabled as default django debugger preferred over werkzeug debugger
## python manage.py runserver_plus 0.0.0.0:8000
python manage.py runserver 0.0.0.0:8000
