# Generated by Django 2.2.13 on 2020-06-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_wagtail', '0009_add_resource_list_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddublincoreresourcepage',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='field_wagtail.FieldDublinCoreResource'),
        ),
    ]
