# Generated by Django 2.2.14 on 2020-07-20 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('field_timeline', '0007_auto_20200616_1009'),
        ('field_wagtail', '0011_delete_timelinepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielddublincoreresourceitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='fielddublincoreresourceitem',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='fielddublincoreresourcelistpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fielddublincoreresourcelistpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='fielddublincoreresourcepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='fielddublincoreresourcepage',
            name='resource',
        ),
        migrations.DeleteModel(
            name='FieldDublinCoreResource',
        ),
        migrations.DeleteModel(
            name='FieldDublinCoreResourceItem',
        ),
        migrations.DeleteModel(
            name='FieldDublinCoreResourceListPage',
        ),
        migrations.DeleteModel(
            name='FieldDublinCoreResourcePage',
        ),
    ]
