# Generated by Django 2.2.14 on 2020-07-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_wagtail', '0019_resource_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldoralhistory',
            options={'verbose_name': 'Oral History',
                     'verbose_name_plural': 'Oral Histories'},
        ),
        migrations.AddField(
            model_name='fieldtimelineevent',
            name='next_event',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='previous_event',
                to='field_wagtail.FieldTimelineEvent'
            ),
        ),
    ]
