# Generated by Django 2.2.15 on 2021-05-12 12:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('field_wagtail', '0026_alt_text_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldimage',
            name='caption',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
