# Generated by Django 2.2.23 on 2022-09-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_game', '0005_auto_20220923_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='farmerA',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='farmerB',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
