# Generated by Django 2.2.23 on 2022-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_game', '0007_gameevent_infected_cow'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgame',
            name='control_group',
            field=models.BooleanField(default=False),
        ),
    ]
