# Generated by Django 2.2.23 on 2023-01-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_game', '0009_farmer_games_played'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='games_played',
            new_name='gamesPlayed',
        ),
    ]
