# Generated by Django 2.2.14 on 2020-07-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('field_wagtail', '0015_fieldtimelineeventitem_fieldtimelinepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtimelineresourceimage',
            options={'verbose_name': 'Timeline Resource'},
        ),
        migrations.AlterField(
            model_name='fieldtimelineresourceimage',
            name='resource',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='related_images',
                to='field_wagtail.FieldTimelineResource'
            ),
        ),
    ]
