# Generated by Django 2.2.14 on 2020-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_wagtail', '0016_related_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtimelineresourceimage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
