# Generated by Django 2.2.14 on 2020-07-27 20:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('field_wagtail', '0017_fieldtimelineresourceimage_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtimelineresource',
            options={},
        ),
        migrations.AlterField(
            model_name='fieldtimelineresourceimage',
            name='resource',
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='related_images',
                to='field_wagtail.FieldTimelineResource'),
        ),
    ]
