version: '3'

volumes:
  django_media: {}
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}

services:

  # Required - Nginx Ingress
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - django_media:/usr/share/nginx/media:ro

  django:
    build:
      context: ../
      dockerfile: ./compose/production/django/Dockerfile
    image: field_liv_django
    container_name: field_liv_django
    volumes:
      - django_media:/app/field/media
    depends_on:
      - postgres
      - elasticsearch
    env_file:
      - .env
    command: /start
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: field-wt.co.uk/
      LETSENCRYPT_HOST: field-wt.co.uk/
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 8000

  db:
    image: postgres
    restart: always

  postgres:
    build:
      context: ../
      dockerfile: ./compose/production/postgres/Dockerfile
    image: field_liv_postgres
    container_name: field_liv_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "5432"

#  postgres:
#    image: postgres
#    restart: always
#    container_name: postgres
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      PGDATA: /var/lib/postgresql/data/pgdata
#    env_file:
#      - .env
#    volumes:
#      - ../volumes/postgres/data:/var/lib/postgresql/data/
#    expose:
#      - "5432"

  # Optional - Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1 # Specify app required version
    container_name: field_liv_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ../volumes/elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"

# Required - Openstack networking - note the indentation level
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442
