volumes:
  django_media: {}


services:

  ## To define the ingress point for a domain, see the tomcat
  ## example below. The following will route project_domain.kdl.kcl.ac.uk
  ## to the specified container on port 8080.
  ##
  ##  environment:
  ##    VIRTUAL_HOST: "project_domain.kdl.kcl.ac.uk"
  ##    VIRTUAL_PROTO: http
  ##    VIRTUAL_PORT: 8080

  # Required - Nginx Ingress
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - django_media:/usr/share/nginx/media:ro

  django:
    build:
      context: .
      dockerfile: ./openstack/django/Dockerfile
    image: field_liv_django
    container_name: field_django
    volumes:
      - django_media:/app/field/media
    depends_on:
      - postgres
      - elasticsearch
    env_file:
      - .env
    command: /start
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: localhost
      LETSENCRYPT_HOST: localhost
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 8001


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  # Optional - Postgres
#  postgres:
#    build:
#      context: .
#      dockerfile: ./compose/production/postgres/Dockerfile
#    image: field_liv_postgres
#    container_name: field_liv_postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data:Z
#      - postgres_data_backups:/backups:z
#    env_file:
#      - ./.envs/.liv/.postgres
#    restart: unless-stopped

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - ../volumes/postgres/data:/var/lib/postgresql/data/
    expose:
      - "5432"

  # Optional - Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1 # Specify app required version
    container_name: field_liv_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ../volumes/elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"



# Required - Openstack networking - note the indentation level
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442
