# Generated by Django 2.2.23 on 2022-06-20 13:46

from django.db import migrations


def default_event_types(apps, schema_editor):
    EventType = apps.get_model('field_game', 'EventType')
    if EventType.objects.filter(event_type="Trade").count() < 1:
        EventType(event_type="Trade").save()
    if EventType.objects.filter(event_type="Join BFree").count() < 1:
        EventType(event_type="Join BFree").save()
    if EventType.objects.filter(event_type="Infection").count() < 1:
        EventType(event_type="Infection").save()


class Migration(migrations.Migration):
    dependencies = [
        ('field_game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_event_types),
    ]
