# Generated by Django 2.2.23 on 2022-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_game', '0003_remove_seedphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgame',
            name='seed',
            field=models.FloatField(default=0.0),
        ),
    ]
