# Generated by Django 2.2.23 on 2022-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_game', '0004_fieldgame_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgame',
            name='creator_sessionid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='creator_sessionid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
