# Generated by Django 2.2.23 on 2022-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_game', '0006_gameevent_farmers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='infected_cow',
            field=models.BooleanField(default=False),
        ),
    ]
