# Generated by Django 2.2.23 on 2023-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_game', '0008_fieldgame_control_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farmerID',
            new_name='playerID',
        ),
        migrations.AddField(
            model_name='farmer',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldgame',
            name='control_group',
            field=models.BooleanField(default=True),
        ),
    ]
