# Generated by Django 2.2.23 on 2023-04-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_game', '0010_auto_20230113_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgame',
            name='played_before',
            field=models.BooleanField(default=False),
        ),
    ]
