# Generated by Django 2.2.23 on 2023-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_game', '0012_fieldgame_infection_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='control_group',
            field=models.BooleanField(default=True),
        ),
    ]
