FROM nginx:stable-alpine

COPY ./compose/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./compose/nginx/robots.txt /usr/share/nginx/robots.txt
COPY ./compose/nginx/certs /usr/share/nginx/certs
