# Generated by Django 2.2.14 on 2020-07-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_timeline', '0007_auto_20200616_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtimelineevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fieldtimelineevent',
            name='linked_events',
        ),
        migrations.RemoveField(
            model_name='fieldtimelineevent',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='fieldtimelineevent',
            name='timelineslide_ptr',
        ),
        migrations.DeleteModel(
            name='FieldTimelineCategory',
        ),
        migrations.DeleteModel(
            name='FieldTimelineEvent',
        ),
        migrations.DeleteModel(
            name='FieldTimelineResource',
        ),
        migrations.DeleteModel(
            name='TimelineSlide',
        ),
    ]
