# Generated by Django 2.2.14 on 2020-07-20 14:10

import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('dublincore_resource', '0004_auto_20191211_1917'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinCoreImage',
            fields=[
                ('dublincoreresource_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True, primary_key=True,
                     serialize=False,
                     to='dublincore_resource.DublinCoreResource')
                 ),
                ('wagtail_image', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='wagtailimages.Image')
                 ),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Resource',
            },
            bases=('dublincore_resource.dublincoreresource',),
        ),
        migrations.CreateModel(
            name='TimelineEventWithDCImageSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=256)),
                ('start_date_year', models.IntegerField(default=0)),
                ('start_date_month', models.IntegerField(default=0)),
                ('start_date_day', models.IntegerField(default=0)),
                ('end_date_year', models.IntegerField(default=0)),
                ('end_date_month', models.IntegerField(default=0)),
                ('end_date_day', models.IntegerField(default=0)),
                ('headline', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('resource',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='+',
                                   to='django_kdl_timeline.DublinCoreImage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='TimelinePage',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='wagtailcore.Page')
                 ),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TimelineSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=256)),
                ('start_date_year', models.IntegerField(default=0)),
                ('start_date_month', models.IntegerField(default=0)),
                ('start_date_day', models.IntegerField(default=0)),
                ('end_date_year', models.IntegerField(default=0)),
                ('end_date_month', models.IntegerField(default=0)),
                ('end_date_day', models.IntegerField(default=0)),
                ('headline', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEventWithDCImageItem',
            fields=[
                ('timelineeventwithdcimagesnippet_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True, primary_key=True,
                     serialize=False,
                     to='django_kdl_timeline.TimelineEventWithDCImageSnippet')
                 ),
                ('sort_order',
                 models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='related_events',
                    to='django_kdl_timeline.TimelinePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('django_kdl_timeline.timelineeventwithdcimagesnippet',
                   models.Model),
        ),
    ]
