# Generated by Django 2.2.14 on 2020-07-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_kdl_timeline', '0002_wagtail_dc_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublincoreimage',
            name='wagtail_image',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='wagtailimages.Image'
            ),
        ),
    ]
